exper_name: "circle_packing"
description: "n = 26 in unit square"
save_dir: "/mollm_results/"
save_suffix: "circle_packing"
initial_pop: "random1" # best100, worst100, random1 ~ 5
resume: False

model:
  name: gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.0
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
  max_new_tokens: 1024
model_collaboration: True

goals: [radii]
optimization_direction: [max]
prompt_info_path: /MCCE/problem/circle_packing/prompt_info.yaml
### Important ###
evalutor_path: problem.circle_packing.evaluator

dpo_script_path: /MCCE/tools/makerldata_circle_embed.py

optimization: 
  pop_size: 50
  eval_budget: 5000



