exper_name: "7.16, with genetic_gfn as au model, 40 main + 32 + 8 au after oracle calls > 0, and ga inside gfn added"
description: "None single model"
save_dir: "/root/src/mollm_results/pmo"
save_suffix: "0828_pmo_noexp"

resume: False

model:
  name: zgca,gemini-2.5-flash-nothinking      #  gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  # name2: zgca,gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
use_au: False  # If True, this will use au model, set to false if you only want to use one LLM

goals: [sa,drd2,qed,gsk3b,jnk3]
optimization_direction: [min,min,max,min,max]
prompt_info_path: /root/src/MOLLM/problem/molecules/molecule.yaml
### Important ###
evalutor_path: problem.molecules.evaluator

optimization: 
  pop_size: 50
  eval_budget: 10000



