exper_name: "Multi-objective molecule optimization with MCCE"
description: "Use original selection, which uses current pop to select"
save_dir: "/mollm_results/exp"
save_suffix: "0919_exp0.1"

cal_div: True
resume: False
early_stopping: False
model:
  name: gpt-4o-2024-05-13   #  gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  prompt_module: Prompt
  #temperature: 1.
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 

model_collaboration: True

goals: [sa,drd2,qed,gsk3b,jnk3]
optimization_direction: [min,min,max,min,max]
prompt_info_path: MCCE/problem/molecules/molecule.yaml
### Important ###
evalutor_path: problem.molecules.evaluator

optimization: 
  pop_size: 50
  eval_budget: 5000



