exper_name: "MOTSP"
description: "Multi-Objective Traveling Salesman Problem with 100 cities"
save_dir: "motsp_Results"
save_suffix: "motsp"
initial_pop: "random1" # best100, worst100, random1 ~ 5
resume: False

model:
  name: gemini-2.5-flash-nothinking 
  prompt_module: Prompt
  experience_prob: 0.0
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
  max_new_tokens: 1024

model_collaboration: True

goals: [distance_obj1, distance_obj2]
optimization_direction: [min, min]
prompt_info_path: problem/motsp/prompt_info.yaml
### Important ###
evalutor_path: problem.motsp.evaluator

dpo_script_path: /MCCE/tools/makerldata_motsp_embed.py

optimization: 
  pop_size: 50
  eval_budget: 8000



