exper_name: "5.28 not repeated mols and parents use nsga_so_select"
save_dir: "/home/hp/src/mollm_results/exp"
save_suffix: "0609_random1_nsga_so_select"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: zgca,gemini-2.5-flash
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 


goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 50
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/hp/src/MOLLM/data/goals5.json"

init_datset: ZINC



