exper_name: "testing only three offsprining each llm calls"
save_dir: "/home/msrai4srl4s/nian/results/off"
save_suffix: "0124_3off_0820"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: chatgpt
  prompt_module: Prompt
  experience_prob: 0.
  crossover_prob: 0.8
  mutation_prob: 0.2 #0.25
  explore_prob: 0. #0.25


goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 51
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/msrai4srl4s/nian/MOLLM/data/goals5.json"

init_datset: ZINC



