exper_name: "best_f selection 0.5 + 0.5 pareto selection, 0.0,0.8,0.2,0  for exp, cross, mutate and explore"
save_dir: "/home/hp/mollm_results/deepseek"
save_suffix: "0313_"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: deepseek
  prompt_module: Prompt
  experience_prob: 0.
  crossover_prob: 0.8
  mutation_prob: 0.2 #0.25
  explore_prob: 0. #0.25


goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 50
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/hp/MOLLM/data/goals5.json"

init_datset: ZINC



