exper_name: "MOCVRP"
description: "Multi-Objective Capacitated Vehicle Routing Problem with 200 customers"
save_dir: "MOCVRP_Results"
save_suffix: "mocvrp"
initial_pop: "random1" # best100, worst100, random1 ~ 5
resume: False

model:
  name: gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.0
  crossover_prob: 0.8
  mutation_prob: 0.2
  explore_prob: 0.
  max_new_tokens: 1024

model_collaboration: True
use_solver: False

goals: [total_distance, makespan]
optimization_direction: [min, min]
prompt_info_path: problem/mocvrp/prompt_info.yaml
### Important ###
evalutor_path: problem.mocvrp.evaluator

dpo_script_path: /MCCE/tools/makerldata_mocvrp_embed.py

optimization:
  pop_size: 50
  eval_budget: 1000